### ISSUE TITLE
Use typeof window === "undefined" and link to github on npm

### ISSUE THREAD

**Issue by approots** [eMarketerOSS/simple-react-intersection-observer#2]
Excellent little library. Thanks so much.

Just a couple of suggestions:

1. The conditional for server-side rendering checks for `global.__SERVER__ ` which I didn't have defined. Perhaps check for `typeof window === "undefined"` instead.
2. I didn't see a link to the github repo on npm.

**Comment by LiamEderzeel** [comment]
I changed `useObserver` as follows to get server-side rendering to work as expected.
```js
this.useObserver = 	typeof window !== "undefined" &&
			'IntersectionObserver' in window &&
			'IntersectionObserverEntry' in window &&
			'intersectionRatio' in window.IntersectionObserverEntry.prototype &&
			'isIntersecting' in window.IntersectionObserverEntry.prototype;
```

**Comment by semsogutlu** [comment]
Hey @LiamEderzeel, @approots Version 0.1.13 uses typeof window === "undefined" instead of global.__SERVER__ variable.

I also added github link to npm. 

Thank you so much for pointing this out!
